### ISSUE TITLE
understand t-tests

### ISSUE THREAD

**Issue by beanumber** [liwencong1995/SDS-Capstone-Zebrafish#2]
Figure out what the t-tests that were run on Morgan's poster from this summer were testing.

**Comment by beanumber** [comment]
It seems like you got pretty close to understanding this. Are you confident this is done?

**Comment by ShuliHuhahaha** [comment]
She tested on the distribution of parameter r, so we know which landmark is different. It is one of the step of the Landmark method. However, we hope to find a better method which would be able to give more information on the structure of the brain.
